server:
  port: 8089

spring:
  kafka:
    bootstrap-servers: localhost:9092

    consumer:
      group-id: notification-service-group
      auto-offset-reset: earliest
      enable-auto-commit: false

      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer

      properties:
        # This tells Kafka: "I don't care what the sender called the class"
        spring.json.use.type.headers: false
        # This tells Kafka: "Trust all data coming in"
        spring.json.trusted.packages: "*"
        # This maps the incoming data specifically to YOUR DTO
        spring.json.value.default.type: com.example.NotificationService.dto.OrderCreatedEvent

    listener:
      ack-mode: record

  mail:
    host: smtp.gmail.com
    port: 587
    username: zakariachajae@gmail.com
    password: kxwxktzstbunorjz
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
