server:
  port: 8081
spring:
  datasource:
    url: jdbc:mysql://product-db:3306/product_db?createDatabaseIfNotExist=true
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
eureka:
  client:
    service-url:
      defaultZone: http://discovery-service:8761/eureka/
